---
application_name: Reloader Pro
business_name: Still River Software Company, LLC
business_address: |-
  126 Crooked Trail Ext
  Woodstock, CT 06281
domain: reloaderpro.com
support_email: support@stillriversoftware.com
default_from_email: ReloaderPro <no-reply@reloaderpro.com>
background_job_processor: solid_queue
email_provider: mailjet
account_types: both
apns: false
fcm: false
integrations:
omniauth_providers:
payment_processors:
multitenancy:
gems:
